### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by alan196** [litnimax/odoo_asterisk#1]
Hello, 

I have seen your talk in Odoo experience in Belgium and I'm really interested in contribute with this modules, can you give me your contact information. I already have a customer looking for this functionality and I would like to talk with you.

My email and Hangout is alan.ramos@jarsa.com.mx

Thanks in advance

**Comment by litnimax** [comment]
* https://apps.odoo.com/apps/modules/12.0/asterisk_calls/
* https://apps.odoo.com/apps/modules/12.0/asterisk_base/
