### ISSUE TITLE
Installation Steps not clear to me

### ISSUE THREAD

**Issue by voipsense** [litnimax/odoo_asterisk#10]
Hi, is very good job
but it's not clear to me the installation way , can plz give me more details 
_ i need docker ?
- where i put the files ?
- i need fresh install odoo 10 before ?

**Comment by litnimax** [comment]
Sorry the code from this repo is not supported.

**Comment by litnimax** [comment]
Please have a look https://apps.odoo.com/apps/modules/10.0/asterisk_base/
