### ISSUE TITLE
Reload AMI Broker

### ISSUE THREAD

**Issue by hokaspb** [litnimax/odoo_asterisk#9]
<group string="Asterisk Settings">
          <group>
            <field name="no_asterisk"/>
            <button icon="fa-gears" type="object" name="reload_ami_broker"
                    string="Reload AMI Broker"/>
          </group>
          <group>

AttributeError: type object 'asterisk.settings' has no attribute 'reload_ami_broker'

**Comment by litnimax** [comment]
The code from this repo is not supported.

**Comment by litnimax** [comment]
Look here - https://apps.odoo.com/apps/modules/10.0/asterisk_base/

**Comment by hokaspb** [comment]
59.7z  passwd : ???


пн, 24 дек. 2018 г. в 00:18, litnimax <notifications@github.com>:

**Comment by hokaspb** [comment]
59 - это моя ошибка. Извините, промахнулся
.

пн, 24 дек. 2018 г. в 13:04, Vladimir A <hoka.spb@gmail.com>:
